#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=/

SCRIPT_ROOT=jhalfs

SRC_DIR=${ROOT}sources

VERSION=2.06
PKG_DEST=${SRC_DIR}/859-grub

PACKAGE=grub-2.06.tar.xz
source ${ROOT}${SCRIPT_ROOT}/packInstall.sh
export -f packInstall
cd $SRC_DIR
PKGDIR=$(tar -tf $PACKAGE | head -n1 | sed 's@^./@@;s@/.*@@')
export PKGDIR VERSION PKG_DEST

if [ -d "$PKGDIR" ]; then rm -rf $PKGDIR; fi
if [ -d "$PKG_DEST" ]; then rm -rf $PKG_DEST; fi
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"


tar -xf $PACKAGE
cd $PKGDIR
SECONDS=${PREV_SEC}

# Start of LFS book script
unset {C,CPP,CXX,LD}FLAGS
patch -Np1 -i ../grub-2.06-upstream_fixes-1.patch
./configure --prefix=/usr          \
            --libdir=/usr/lib64    \
            --sysconfdir=/etc      \
            --disable-efiemu       \
            --disable-werror
make
mkdir -pv $PKG_DEST/{boot,etc}
mkdir -pv $PKG_DEST/usr/{bin,include,lib,lib64/pkgconfig,sbin}
mkdir -pv $PKG_DEST/usr/share/{doc,info,bash-completion/completions}
mkdir -pv $PKG_DEST/usr/share/man/man{1..8}
ln -sv usr/sbin $PKG_DEST
ln -sv usr/bin  $PKG_DEST
ln -sv usr/lib  $PKG_DEST
ln -sv usr/lib64  $PKG_DEST
make -j1 DESTDIR=$PKG_DEST install
mv -v $PKG_DEST/etc/bash_completion.d/grub $PKG_DEST/usr/share/bash-completion/completions
for dir in $PKG_DEST/usr/share/man/man{1..8} \
           $PKG_DEST/usr/share/bash-completion{/completions,} \
           $PKG_DEST/usr/share/{doc,info,man,} \
           $PKG_DEST/usr/lib64/pkgconfig \
           $PKG_DEST/usr/{lib,lib64,bin,sbin,include} \
           $PKG_DEST/{boot,etc}; do
  [ -d "$dir" ] && [ -z "$(ls $dir)" ] && rmdir -v $dir
done
rm -v $PKG_DEST/{lib,lib64,bin,sbin}

rm -rf $PKG_DEST/var/{run,lock}

[ -d $PKG_DEST/var ] && [ -z "$(ls $PKG_DEST/var)" ] && rmdir -v $PKG_DEST/var
PREV_SEC=${SECONDS}
packInstall
SECONDS=${PREV_SEC}
rm -rf $PKG_DEST
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
cd $SRC_DIR
rm -rf $PKGDIR
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi
exit
