#!/bin/bash
set +h
set -e


PREV_SEC=${SECONDS}
      
ROOT=/

SCRIPT_ROOT=jhalfs

SRC_DIR=${ROOT}sources

VERSION=6.0.2
PKG_DEST=${SRC_DIR}/877-04-pacman

PACKAGE=pacman-6.0.2.tar.xz
source ${ROOT}${SCRIPT_ROOT}/packInstall.sh
export -f packInstall
cd $SRC_DIR
PKGDIR=$(tar -tf $PACKAGE | head -n1 | sed 's@^./@@;s@/.*@@')
export PKGDIR VERSION PKG_DEST

if [ -d "$PKGDIR" ]; then rm -rf $PKGDIR; fi
if [ -d "$PKG_DEST" ]; then rm -rf $PKG_DEST; fi
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"


tar -xf $PACKAGE
cd $PKGDIR
SECONDS=${PREV_SEC}

# Start of LFS book script
mkdir build
cd build
meson --prefix=/usr        \
      --libdir=/usr/lib64  \
      -Dcrypto=openssl
ninja
DESTDIR=$PKG_DEST ninja install
PREV_SEC=${SECONDS}
packInstall
SECONDS=${PREV_SEC}
rm -rf "$PKG_DEST"
sed -e 's/\([^!]\)strip/\1!strip/' \
    -e 's/\([^!]\)zipman/\1!zipman/' \
    -e 's/\([^!]\)libtool/\1!libtool/' \
    -i /etc/makepkg.conf
cat >> /etc/makepkg.conf << EOF
BUILDDIR=/sources
PKGDEST=/var/lib/packages
PACKAGER="Pierre Labastie <lnimbus@club-internet.fr<"
EOF
cat >> /etc/pacman.conf << EOF
DBPath   = /var/lib/pacman/
CacheDir = /var/cache/pacman/pkg/
LogFile  = /var/log/pacman.log
SigLevel = Never
EOF

echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
cd $SRC_DIR
rm -rf $PKGDIR
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi
exit
