#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=/

SCRIPT_ROOT=jhalfs

SRC_DIR=${ROOT}sources

VERSION=6.3.4
PKG_DEST=${SRC_DIR}/1002-kernel

PACKAGE=linux-6.3.4.tar.xz
source ${ROOT}${SCRIPT_ROOT}/packInstall.sh
export -f packInstall
cd $SRC_DIR
PKGDIR=$(tar -tf $PACKAGE | head -n1 | sed 's@^./@@;s@/.*@@')
export PKGDIR VERSION PKG_DEST

if [ -d "$PKGDIR" ]; then rm -rf $PKGDIR; fi
if [ -d "$PKG_DEST" ]; then rm -rf $PKG_DEST; fi
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"


tar -xf $PACKAGE
cd $PKGDIR
SECONDS=${PREV_SEC}

# Start of LFS book script
make mrproper
cp -v ../kernel-config .config
make
mkdir -pv $PKG_DEST/{boot,etc}
mkdir -pv $PKG_DEST/usr/{bin,include,lib,lib64/pkgconfig,sbin}
mkdir -pv $PKG_DEST/usr/share/{doc,info,bash-completion/completions}
mkdir -pv $PKG_DEST/usr/share/man/man{1..8}
ln -sv usr/sbin $PKG_DEST
ln -sv usr/bin  $PKG_DEST
ln -sv usr/lib  $PKG_DEST
ln -sv usr/lib64  $PKG_DEST
make -j1 INSTALL_MOD_PATH=$PKG_DEST modules_install

cp -v arch/x86/boot/bzImage $PKG_DEST/boot/vmlinuz-6.3.4-future-systemd
cp -v System.map $PKG_DEST/boot/System.map-6.3.4
cp -v .config $PKG_DEST/boot/config-6.3.4
install -d $PKG_DEST/usr/share/doc/linux-6.3.4
cp -r Documentation/* $PKG_DEST/usr/share/doc/linux-6.3.4
for dir in $PKG_DEST/usr/share/man/man{1..8} \
           $PKG_DEST/usr/share/bash-completion{/completions,} \
           $PKG_DEST/usr/share/{doc,info,man,} \
           $PKG_DEST/usr/lib/pkgconfig \
           $PKG_DEST/usr/{lib,bin,sbin,include} \
           $PKG_DEST/{boot,etc}; do
  [ -d "$dir" ] && [ -z "$(ls $dir)" ] && rmdir -v $dir
done
rm -v $PKG_DEST/{lib,lib64.bin,sbin}

rm -rf $PKG_DEST/var/{run,lock}

[ -d $PKG_DEST/var ] && [ -z "$(ls $PKG_DEST/var)" ] && rmdir -v $PKG_DEST/var
PREV_SEC=${SECONDS}
packInstall
SECONDS=${PREV_SEC}
rm -rf $PKG_DEST
install -v -m755 -d /etc/modprobe.d
cat > /etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf

install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

# End /etc/modprobe.d/usb.conf
EOF
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
cd $SRC_DIR
rm -rf $PKGDIR
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi
exit
