#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=$LFS/

SCRIPT_ROOT=jhalfs

SRC_DIR=${ROOT}sources

VERSION=3.11.3
PKG_DEST=${SRC_DIR}/708-Python

PACKAGE=Python-3.11.3.tar.xz
cd $SRC_DIR
PKGDIR=$(tar -tf $PACKAGE | head -n1 | sed 's@^./@@;s@/.*@@')
export PKGDIR VERSION PKG_DEST

if [ -d "$PKGDIR" ]; then rm -rf $PKGDIR; fi
if [ -d "$PKG_DEST" ]; then rm -rf $PKG_DEST; fi
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"


tar -xf $PACKAGE
cd $PKGDIR
SECONDS=${PREV_SEC}

# Start of LFS book script
patch -Np1 -i ../python-site-packages.patch
./configure --prefix=/usr        \
            --libdir=/usr/lib64  \
            --enable-shared      \
            --without-ensurepip  \
            --with-platlibdir=lib64
make
make -j1 install
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
cd $SRC_DIR
rm -rf $PKGDIR
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi
exit
